project:
  type: website
  output-dir: docs

website:
  title: "Figure Friday 2024 - week 34"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/eveliinahampus/plotly-dash

format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto


